# Generated by Django 5.2.7 on 2025-11-21 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('LOGS', 'System Logs'), ('AUDIT_LOGS', 'Audit Logs'), ('USER_DATA', 'User Profile Data'), ('PAYMENT_DATA', 'Payment Records'), ('SUBMISSIONS', 'Project Submissions'), ('CERTIFICATES', 'Certificates')], max_length=50, unique=True)),
                ('retention_days', models.IntegerField(help_text='Number of days to retain data')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('legal_requirement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Retention Policies',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('effective_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('effective_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Terms of Service',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy_version', models.CharField(max_length=20)),
                ('terms_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('SIGNUP', 'User Signup'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change'), ('DATA_EXPORT', 'Data Export Requested'), ('ACCOUNT_DELETE', 'Account Deletion Requested'), ('PAYMENT', 'Payment Made'), ('ENROLLMENT', 'Enrollment Status Change'), ('SUBMISSION', 'Project Submission'), ('GRADE', 'Grade Assigned'), ('ADMIN_ACTION', 'Admin Action')], max_length=50)),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='compliance__timesta_accae9_idx'), models.Index(fields=['user', '-timestamp'], name='compliance__user_id_71a297_idx'), models.Index(fields=['action', '-timestamp'], name='compliance__action_26c18c_idx')],
            },
        ),
    ]
