# Generated by Django 5.2.7 on 2025-11-07 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_assigned_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('trainer', 'Trainer'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], default='student', max_length=20),
        ),
    ]
