# Generated by Django 5.2.7 on 2025-11-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_assigned_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
