# Generated by Django 5.2.7 on 2025-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_github_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_deletion_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='anonymized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_retention_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enrollment_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ENROLLED', 'Enrolled'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='graduation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='privacy_version',
            field=models.CharField(blank=True, default='1.0', max_length=20),
        ),
    ]
