"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import dj_database_url
import stripe
from decouple import config
# JWT Settings
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

stripe.api_key = STRIPE_SECRET_KEY

# Student Database Configuration (for DP track schema provisioning)
STUDENT_DB_HOST = config("STUDENT_DB_HOST", default="localhost")
STUDENT_DB_PORT = config("STUDENT_DB_PORT", default="5432")
STUDENT_DB_NAME = config("STUDENT_DB_NAME", default="apranova_students")
STUDENT_DB_ADMIN_USER = config("STUDENT_DB_ADMIN_USER", default="postgres")
STUDENT_DB_ADMIN_PASSWORD = config("STUDENT_DB_ADMIN_PASSWORD", default="")

# GitHub OAuth Settings
GITHUB_CLIENT_ID = config("GITHUB_CLIENT_ID", default="")
GITHUB_CLIENT_SECRET = config("GITHUB_CLIENT_SECRET", default="")
GITHUB_REDIRECT_URI = config("GITHUB_REDIRECT_URI", default="http://localhost:8000/api/github/callback")
GITHUB_WEBHOOK_SECRET = config("GITHUB_WEBHOOK_SECRET", default="")

# GitHub Organization Settings
GITHUB_ORGANIZATION = config("GITHUB_ORGANIZATION", default="apranova-bootcamp")
GITHUB_ORG_TOKEN = config("GITHUB_ORG_TOKEN", default="")
GITHUB_USE_ORGANIZATION = config("GITHUB_USE_ORGANIZATION", default="True") == "True"
BACKEND_URL = config("BACKEND_URL", default="http://localhost:8000")

# Slack Settings
SLACK_WEBHOOK_URL = config("SLACK_WEBHOOK_URL", default="")
SLACK_BOT_TOKEN = config("SLACK_BOT_TOKEN", default="")
SLACK_ENABLED = config("SLACK_ENABLED", default=False, cast=bool)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-2z8!!969w^qmh+ac9%3%1w4d1j*t0c!4kut^&8tkc2!c!8q(=(",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="apra-nova-backend-main.onrender.com,localhost,backend,169.254.172.3,.amplifyapp.com,127.0.0.1,8saxivdpb6.ap-south-1.awsapprunner.com").split(",")

# Enable automatic slash appending for better URL handling
APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    # Django defaults
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for allauth
    # Third-party apps
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_yasg",
    # Django allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    # dj-rest-auth
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # Your custom apps
    "accounts",
    "curriculum",
    "quizzes",
    "compliance",
    "submissions",
    # stripe
    "payments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # ADD THIS LINE
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (User uploaded files)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# APROVOVA Reports Directory - Centralized location for all reports
APROVOVA_REPORTS_DIR = BASE_DIR / "APROVOVA"
APROVOVA_USER_REPORTS_DIR = APROVOVA_REPORTS_DIR / "user_reports"
APROVOVA_PAYMENT_REPORTS_DIR = APROVOVA_REPORTS_DIR / "payment_reports"
APROVOVA_BATCH_REPORTS_DIR = APROVOVA_REPORTS_DIR / "batch_reports"
APROVOVA_ANALYTICS_REPORTS_DIR = APROVOVA_REPORTS_DIR / "analytics_reports"

# Create APROVOVA directories if they don't exist
import os
for directory in [
    APROVOVA_REPORTS_DIR,
    APROVOVA_USER_REPORTS_DIR,
    APROVOVA_PAYMENT_REPORTS_DIR,
    APROVOVA_BATCH_REPORTS_DIR,
    APROVOVA_ANALYTICS_REPORTS_DIR,
]:
    os.makedirs(directory, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom User Model
AUTH_USER_MODEL = "accounts.CustomUser"


# Django Sites Framework
SITE_ID = 1


# Authentication Backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # SessionAuthentication removed to avoid CSRF issues with Next.js proxy
        # "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
}



# Frontend URL
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",  # Added for payment page
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",  # Added for payment page
    "https://9f91d0a1.apranovaui-main.pages.dev",
    "https://apranovaui-main.pages.dev",
    "https://main.d1y4jib944emzx.amplifyapp.com",
    "https://main.d1mmt360isf99v.amplifyapp.com"
]
CORS_ALLOW_CREDENTIALS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",  # Added for payment page
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",  # Added for payment page
    "https://9f91d0a1.apranovaui-main.pages.dev",
    "https://apranovaui-main.pages.dev",
    "https://main.d1y4jib944emzx.amplifyapp.com",
    "https://main.d1mmt360isf99v.amplifyapp.com"
]


# Django Allauth Settings
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "none"  # Disable email verification for development
ACCOUNT_UNIQUE_EMAIL = True

# Skip intermediate allauth pages - directly redirect to OAuth provider
SOCIALACCOUNT_LOGIN_ON_GET = True

# Social Auth Providers Configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "APP": {
            "client_id": config("GOOGLE_CLIENT_ID", default=""),
            "secret": config("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
    },
    "github": {
        "SCOPE": [
            "user",
            "email",
        ],
        "APP": {
            "client_id": config("GITHUB_CLIENT_ID", default=""),
            "secret": config("GITHUB_CLIENT_SECRET", default=""),
            "key": "",
        },
    },
}


# Redirect URLs
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")
LOGIN_REDIRECT_URL = "/accounts/oauth/callback/"  # Our custom callback handler
ACCOUNT_LOGOUT_REDIRECT_URL = FRONTEND_URL


# Email Configuration
# For development: use console backend (prints emails to logs)
# For production: use SMTP backend with real credentials
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="noreply@apranova.com")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@apranova.com")
SERVER_EMAIL = config("SERVER_EMAIL", default="admin@apranova.com")

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# dj-rest-auth settings for JWT
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'auth-token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh-token',
    'JWT_AUTH_HTTPONLY': False,
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.UserSerializer',
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # DEBUG level enable hai
    },
    'loggers': {
        'accounts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Production Security Settings
if not DEBUG:
    # HTTPS/SSL Settings
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Proxy settings for production
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
