# Generated by Django 5.2.7 on 2025-11-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_create_repo',
            field=models.BooleanField(default=False, help_text='Automatically create GitHub repo when student starts project'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_template_repo',
            field=models.CharField(blank=True, help_text="GitHub template repo (e.g., 'apranova/react-portfolio-template')", max_length=200),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='github_pr_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='github_pr_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='github_pr_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='github_repo_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='github_repo_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='github_repo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='github_pr_url',
            field=models.URLField(blank=True, help_text='GitHub Pull Request URL'),
        ),
    ]
