# Generated by Django 5.2.7 on 2025-11-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_project_auto_create_repo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='Auto-created from webhook'),
        ),
        migrations.AddField(
            model_name='submission',
            name='github_pr_number',
            field=models.IntegerField(blank=True, help_text='GitHub PR number', null=True),
        ),
    ]
